<a href="https://colab.research.google.com/github/alfiyaka/data-science-/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

a = np.array([[1,2],[3,4]])

c = np.arange(15).reshape(3,5)
print (a)


[[1 2]
 [3 4]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
b = np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
a =np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [7]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4
