<a href="https://colab.research.google.com/github/alfiyaka/data-science-/blob/main/program%201%20to%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [4]:
array_from_list=np.array([1,2,3,4,5])
print("array from list:",array_from_list)
array_with_range=np.arange(10)
print("array with range:",array_with_range)
array_with_zeros=np.zeros((3,3))
print("array with zeros:",array_with_range)
zeros_array=np.zeros((3,3))
print("ARRAY OF ZEROS",zeros_array)
ones_array=np.ones((2,5))
print("ARRAY OF ONES",ones_array)

array from list: [1 2 3 4 5]
array with range: [0 1 2 3 4 5 6 7 8 9]
array with zeros: [0 1 2 3 4 5 6 7 8 9]
ARRAY OF ZEROS [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ARRAY OF ONES [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
add_result=np.add(a,b)
print("ADDITION RESULT:",add_result)
sub_result=np.subtract(a,b)
print("SUBTRACTION RESULT:",sub_result)
mul_result=np.multiply(a,b)
print("MULTIPLICATION RESULT:",mul_result)
div_result=np.divide(a,b)
print("DIVISION RESULT:",div_result)

ADDITION RESULT: [5 7 9]
SUBTRACTION RESULT: [-3 -3 -3]
MULTIPLICATION RESULT: [ 4 10 18]
DIVISION RESULT: [0.25 0.4  0.5 ]


In [6]:
array=np.arange(12)
print("orginal array:",array)
reshaped_array=array.reshape(3*4)
print("reshaped array:",reshaped_array)
reshaped_array_2=array.reshape(2*3*2)
print("reshaped array 2:",reshaped_array_2)

orginal array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 2: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
array_2d=np.array([[1,2,3],[4,5,6]])
print("original 2d array:",array_2d)
element=array_2d[1,2]
print("element at (1,2):",element)
subarray=array_2d[1:3,0:2]
print("subarray:",subarray)
column=array_2d[:,1]
print("column:",column)

original 2d array: [[1 2 3]
 [4 5 6]]
element at (1,2): 6
subarray: [[4 5]]
column: [2 5]


In [8]:
array_1d=np.array([1,2,3,4,5,6,7,8,9,10])
print("original 1d array:",array_1d)
mean=np.mean(array_1d)
print("mean:",mean)
median=np.median(array_1d)
print("median:",median)
std_dev=np.std(array_1d)
print("standard deviation:",std_dev)
max_value=np.max(array_1d)
print("maximum value:",max_value)
min_value=np.min(array_1d)
print("minimum value:",min_value)

original 1d array: [ 1  2  3  4  5  6  7  8  9 10]
mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
maximum value: 10
minimum value: 1


In [9]:
matrix1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("matrix 1:",matrix1)
print("matrix 2:",matrix2)
matrix_sum=matrix1+matrix2
print("matrix sum:",matrix_sum)
matrix_diff=matrix1-matrix2
print("matrix difference:",matrix_diff)
matrix_product=np.dot(matrix1,matrix2)
print("matrix product:",matrix_product)
matrix_transpose=np.transpose(matrix1)
print("matrix transpose:",matrix_transpose)
matrix_divison=matrix1/matrix2
print("matrix division:",matrix_divison)
matrix_multiplication=matrix1*matrix2
print("matrix multiplication:",matrix_multiplication)


matrix 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix 2: [[9 8 7]
 [6 5 4]
 [3 2 1]]
matrix sum: [[10 10 10]
 [10 10 10]
 [10 10 10]]
matrix difference: [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
matrix product: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
matrix transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]
matrix division: [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
matrix multiplication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [12]:
x=np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])
print("matrix 1:",x)
print("matrix 2:",y)
a=np.power(x,2)
print("matrix 1 power 2:",a)
b=np.power(y,2)
print("matrix 2 power 2:",b)

matrix 1: [[1 2]
 [3 4]]
matrix 2: [[4 5]
 [6 7]]
matrix 1 power 2: [[ 1  4]
 [ 9 16]]
matrix 2 power 2: [[16 25]
 [36 49]]


In [15]:
two_dimensional_array = np.array([[1, 2, 3, 4],  [5, 6, 7, 8],  [9, 10, 11, 12],  [13, 14, 15, 16]])
excluding_first_row = two_dimensional_array[1:]
excluding_last_column = two_dimensional_array[:, :-1]
column_1_2_in_row_2_3 = two_dimensional_array[1:3, 0:2]
column_2_3 = two_dimensional_array[:, 1:3]
elements_2_3_in_first_row = two_dimensional_array[0, 1:3]
descending_order = two_dimensional_array.ravel()[::-1][4:11]
print("Original 2D array:\n", two_dimensional_array)
print("Elements excluding the first row:\n", excluding_first_row)
print("Elements excluding the last column:\n", excluding_last_column)
print("Elements of the 1st and 2nd column in the 2nd and 3rd row:\n", column_1_2_in_row_2_3)

print("Elements of the 2nd and 3rd column:\n", column_2_3)
print("2nd and 3rd element of the 1st row:\n", elements_2_3_in_first_row)
print("Elements from indices 4 to 10 in descending order:\n", descending_order)

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements excluding the first row:
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements excluding the last column:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Elements of the 1st and 2nd column in the 2nd and 3rd row:
 [[ 5  6]
 [ 9 10]]
Elements of the 2nd and 3rd column:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
2nd and 3rd element of the 1st row:
 [2 3]
Elements from indices 4 to 10 in descending order:
 [12 11 10  9  8  7  6]


In [16]:
A = np.array([[2, 1,-2],[3,0,1],[1,1,-1]])
b = np.array([-3,5,-2])
X = np.linalg.solve(A, b)
print("Matrix A:")
print(A)
print("Vector b:")
print(b)
print("Solution for X:")
print(X)

Matrix A:
[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
Vector b:
[-3  5 -2]
Solution for X:
[ 1. -1.  2.]
